#!/bin/bash

cd $(dirname $0)

while true
do
	./node_modules/.bin/coffee src/index.coffee -c
	result=$?
	if [ $result != 0 ]
	then
		if [ $result == 100 ]
		then
			echo "Restarting."
		else
			echo "Server crashed (return code $result), trying again soon."
			sleep 1
		fi
	else
		exit
	fi
done

